# Generated by Django 5.0.6 on 2024-06-26 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('CodCountry', models.IntegerField(primary_key=True, serialize=False)),
                ('NameCountry', models.CharField(max_length=50)),
                ('GovType', models.CharField(max_length=50)),
                ('Language', models.CharField(max_length=50)),
                ('Continent', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('CodCity', models.IntegerField(primary_key=True, serialize=False)),
                ('NameCity', models.CharField(max_length=50)),
                ('Capital', models.BooleanField()),
                ('CodCountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country')),
            ],
        ),
    ]
